######################################################################
# Automatically generated by qmake (2.01a) Wed Jun 19 18:47:11 2013
######################################################################
TEMPLATE = app
QT	+= widgets
CONFIG	-= console
TARGET	= drm-plus-0.6
QMAKE_CFLAGS	+= -ffast-math -flto
QMAKE_CXXFLAGS	+= -ffast-math -flto
#QMAKE_LFLAGS	+= -g
#QMAKE_CXXFLAGS	+= -g 
RC_ICONS        =  drmplus.ico
RESOURCES       += resources.qrc

DEPENDPATH += .  \
	      scopes-qwt6 \
	      filters \
	      various \
	      output \
	      devices \
	      devices/wavfiles \
	      devices/rawfiles-192-8 \
	      devices/rawfiles-192-16 \
	      devices/rawfiles-192-32 \
	      decoders 

INCLUDEPATH += .  \
	      scopes-qwt6 \
	      filters \
	      various \
	      output \
	      devices \
	      devices/wavfiles \
	      devices/rawfiles-192-8 \
	      devices/rawfiles-192-16 \
	      devices/rawfiles-192-32 \
	      decoders 

#CONFIG += static

# Input
HEADERS += ./radio.h \
	   ./filters/fir-filters.h \
	   ./filters/iir-filters.h \
	   ./filters/fft-filters.h \
           ./various/ringbuffer.h \
           ./various/fft.h \
	   ./various/utilities.h \
	   ./various/program-list.h \
	   ./various/popup-keypad.h \
	   ./various/Xtan2.h \
	   ./output/upconverter.h \
           ./output/audiosink.h \
	   ./scopes-qwt6/virtual-scope.h \
	   ./scopes-qwt6/spectrogramdata.h \
	   ./scopes-qwt6/spectrum-scope.h \
           ./scopes-qwt6/scope.h \
           ./scopes-qwt6/fft-scope.h \
	   ./devices/device-handler.h \
	   ./devices/wavfiles/wavfiles.h \
	   ./devices/wavfiles/wav-reader-base.h \
	   ./devices/wavfiles/wav-reader-conv.h \
	   ./devices/wavfiles/wav-reader-nconv.h \
	   ./devices/rawfiles-192-8/rawfiles-192-8.h \
	   ./devices/rawfiles-192-8/raw-reader-192-8.h \
	   ./devices/rawfiles-192-16/rawfiles-192-16.h \
	   ./devices/rawfiles-192-16/raw-reader-192-16.h \
	   ./devices/rawfiles-192-32/rawfiles-192-32.h \
	   ./devices/rawfiles-192-32/raw-reader-192-32.h \
	   ./decoders/virtual-decoder.h \

FORMS	+= ./drm-receiver.ui \
	   ./devices/filereader-widget.ui \

SOURCES += ./main.cpp \
	   ./radio.cpp \
	   ./filters/fir-filters.cpp \
	   ./filters/iir-filters.cpp \
	   ./filters/fft-filters.cpp \
           ./various/fft.cpp \
	   ./various/popup-keypad.cpp \
	   ./various/utilities.cpp \
	   ./various/program-list.cpp \
	   ./various/Xtan2.cpp \
	   ./output/upconverter.cpp \
           ./output/audiosink.cpp \
	   ./scopes-qwt6/virtual-scope.cpp \
	   ./scopes-qwt6/spectrum-scope.cpp \
           ./scopes-qwt6/scope.cpp \
           ./scopes-qwt6/fft-scope.cpp \
	   ./scopes-qwt6/audio-scope.cpp \
	   ./devices/device-handler.cpp \
	   ./devices/wavfiles/wavfiles.cpp \
	   ./devices/wavfiles/wav-reader-base.cpp \
	   ./devices/wavfiles/wav-reader-conv.cpp \
	   ./devices/wavfiles/wav-reader-nconv.cpp \
	   ./devices/rawfiles-192-8/rawfiles-192-8.cpp \
	   ./devices/rawfiles-192-8/raw-reader-192-8.cpp  \
	   ./devices/rawfiles-192-16/rawfiles-192-16.cpp \
	   ./devices/rawfiles-192-16/raw-reader-192-16.cpp  \
	   ./devices/rawfiles-192-32/rawfiles-192-32.cpp \
	   ./devices/rawfiles-192-32/raw-reader-192-32.cpp  \
	   ./decoders/virtual-decoder.cpp \

unix {
DESTDIR		= ./linux-bin
CONFIG		+= sdrplay
CONFIG		+= rtlsdr
CONFIG		+= hackrf
CONFIG		+= lime
CONFIG		+= drm
CONFIG		+= fm
LIBS		+= -L/usr/lib64
LIBS		+= -L/lib64
INCLUDEPATH	+= /usr/include/qt5/qwt
LIBS		+= -lqwt-qt5 -lrt -lsndfile -lsamplerate -lportaudio -lusb-1.0 -lfftw3f -lfaad_drm -ldl
}

win32 {
DESTDIR		= .
CONFIG		+= sdrplay
CONFIG		+= hackrf
CONFIG		+= rtlsdr
#CONFIG		+= pmsdr
#CONFIG		+= extio
#CONFIG		+= cardreader
CONFIG          += drm
CONFIG          += fm
# includes in mingw differ from the includes in fedora linux
INCLUDEPATH += /usr/i686-w64-mingw32/sys-root/mingw/include
INCLUDEPATH += /usr/i686-w64-mingw32/sys-root/mingw/include/qt5/qwt
INCLUDEPATH += C:\msys32\mingw32\include\qwt
LIBS    += -L/usr/i686-w64-mingw32/sys-root/mingw/lib
LIBS    += -lfftw3f
LIBS    += -lportaudio
LIBS    += -lqwt-qt5
#LIBS    += -lqwt
LIBS    += -lusb-1.0
LIBS    += -lsndfile
LIBS    += -lsamplerate
LIBS    += -lole32
LIBS	+= -lfaad_drm
LIBS    += -lwinmm
}

drm	{
FORMS += ./decoders/drm-decoder/drm-decoder.ui \
	 ./decoders/drm-decoder/technical-data.ui \
	 ./decoders/drm-decoder/audiodata.ui 

DEPENDPATH += decoders/drm-decoder \
	      decoders/drm-decoder/input \
	      decoders/drm-decoder/fac-processor \
	      decoders/drm-decoder/sdc-processor \
	      decoders/drm-decoder/msc-processor \
	      decoders/drm-decoder/msc-processor/data-handling \
	      decoders/drm-decoder/msc-processor/qam4-handler \
	      decoders/drm-decoder/msc-processor/qam16-handler \
	      decoders/drm-decoder/utilities \
	      decoders/drm-decoder/services \
	      decoders/drm-decoder/scopes \
	      decoders/drm-decoder/signal-handling  

INCLUDEPATH += decoders/drm-decoder \
	      decoders/drm-decoder/input \
	      decoders/drm-decoder/fac-processor \
	      decoders/drm-decoder/sdc-processor \
	      decoders/drm-decoder/msc-processor \
	      decoders/drm-decoder/msc-processor/data-handling \
	      decoders/drm-decoder/msc-processor/qam4-handler \
	      decoders/drm-decoder/msc-processor/qam16-handler \
	      decoders/drm-decoder/utilities \
	      decoders/drm-decoder/services \
	      decoders/drm-decoder/scopes \
	      decoders/drm-decoder/signal-handling  

HEADERS += ./decoders/drm-decoder/drm-decoder.h \
	   ./decoders/drm-decoder/basics.h \
	   ./decoders/drm-decoder/wordcollector.h \
	   ./decoders/drm-decoder/frame-handler.h \
	   ./decoders/drm-decoder/input/reader.h \
	   ./decoders/drm-decoder/fac-processor/fac-processor.h \
	   ./decoders/drm-decoder/sdc-processor/sdc-processor.h \
	   ./decoders/drm-decoder/sdc-processor/sdc-handler.h \
	   ./decoders/drm-decoder/msc-processor/msc-processor.h \
	   ./decoders/drm-decoder/msc-processor/msc-handler.h \
	   ./decoders/drm-decoder/msc-processor/qam4-handler/qam4-handler.h \
	   ./decoders/drm-decoder/msc-processor/qam16-handler/qam16-handler.h \
	   ./decoders/drm-decoder/msc-processor/qam16-handler/msc-streamer.h \
	   ./decoders/drm-decoder/msc-processor/qam16-handler/qam16-handler.h \
	   ./decoders/drm-decoder/msc-processor/data-handling/post-processor.h \
	   ./decoders/drm-decoder/msc-processor/data-handling/audio-processor.h \
	   ./decoders/drm-decoder/msc-processor/data-handling/drm-aacdecoder.h \
	   ./decoders/drm-decoder/msc-processor/data-handling/message-processor.h \
	   ./decoders/drm-decoder/msc-processor/data-handling/data-processor.h\
	   ./decoders/drm-decoder/msc-processor/data-handling/virtual-datahandler.h\
	   ./decoders/drm-decoder/msc-processor/data-handling/reed-solomon.h\
	   ./decoders/drm-decoder/msc-processor/data-handling/packet-assembler.h\
	   ./decoders/drm-decoder/msc-processor/data-handling/mot-data.h\
	   ./decoders/drm-decoder/msc-processor/data-handling/galois.h\
	   ./decoders/drm-decoder/msc-processor/data-handling/fec-handler.h\
	   ./decoders/drm-decoder/utilities/checkcrc.h \
	   ./decoders/drm-decoder/utilities/mapper.h \
	   ./decoders/drm-decoder/utilities/prbs.h \
	   ./decoders/drm-decoder/utilities/qam4-metrics.h \
	   ./decoders/drm-decoder/utilities/viterbi-drm.h \
	   ./decoders/drm-decoder/utilities/puncture-tables.h \
	   ./decoders/drm-decoder/utilities/deinterleaver.h \
	   ./decoders/drm-decoder/services/timesyncer.h \
	   ./decoders/drm-decoder/services/freqsyncer.h \
	   ./decoders/drm-decoder/services/time-correlator.h \
	   ./decoders/drm-decoder/scopes/eqdisplay.h \
	   ./decoders/drm-decoder/scopes/iqdisplay.h \
	   ./decoders/drm-decoder/scopes/spectrogramdata.h \
	   ./decoders/drm-decoder/signal-handling/referenceframe.h \
	   ./decoders/drm-decoder/signal-handling/equalizer-base.h \
	   ./decoders/drm-decoder/signal-handling/matrix2.h \
	   ./decoders/drm-decoder/signal-handling/equalizer-1.h \
	   ./decoders/drm-decoder/signal-handling/estimator-base.h \
#	   ./decoders/drm-decoder/signal-handling/equalizer-2.h
	   ./decoders/drm-decoder/signal-handling/estimator-1.h \

SOURCES *= ./decoders/drm-decoder/drm-decoder.cpp \
	   ./decoders/drm-decoder/basics.cpp \
	   ./decoders/drm-decoder/wordcollector.cpp \
	   ./decoders/drm-decoder/frame-handler.cpp \
	   ./decoders/drm-decoder/input/reader.cpp \
	   ./decoders/drm-decoder/fac-processor/fac-processor.cpp \
	   ./decoders/drm-decoder/sdc-processor/sdc-processor.cpp \
	   ./decoders/drm-decoder/sdc-processor/sdc-handler.cpp \
	   ./decoders/drm-decoder/msc-processor/msc-processor.cpp \
	   ./decoders/drm-decoder/msc-processor/msc-handler.cpp \
	   ./decoders/drm-decoder/msc-processor/qam4-handler/qam4-handler.cpp \
	   ./decoders/drm-decoder/msc-processor/qam16-handler/qam16-handler.cpp \
	   ./decoders/drm-decoder/msc-processor/qam16-handler/msc-streamer.cpp \
	   ./decoders/drm-decoder/msc-processor/qam16-handler/qam16-metrics.cpp \
	   ./decoders/drm-decoder/msc-processor/data-handling/post-processor.cpp \
	   ./decoders/drm-decoder/msc-processor/data-handling/audio-processor.cpp \
	   ./decoders/drm-decoder/msc-processor/data-handling/drm-aacdecoder.cpp \
	   ./decoders/drm-decoder/msc-processor/data-handling/message-processor.cpp \
	   ./decoders/drm-decoder/msc-processor/data-handling/data-processor.cpp\
	   ./decoders/drm-decoder/msc-processor/data-handling/virtual-datahandler.cpp\
	   ./decoders/drm-decoder/msc-processor/data-handling/reed-solomon.cpp\
	   ./decoders/drm-decoder/msc-processor/data-handling/packet-assembler.cpp\
	   ./decoders/drm-decoder/msc-processor/data-handling/mot-data.cpp\
	   ./decoders/drm-decoder/msc-processor/data-handling/galois.cpp\
	   ./decoders/drm-decoder/msc-processor/data-handling/fec-handler.cpp\
	   ./decoders/drm-decoder/utilities/checkcrc.cpp \
	   ./decoders/drm-decoder/utilities/mapper.cpp \
	   ./decoders/drm-decoder/utilities/prbs.cpp \
	   ./decoders/drm-decoder/utilities/qam4-metrics.cpp \
	   ./decoders/drm-decoder/utilities/viterbi-drm.cpp \
	   ./decoders/drm-decoder/utilities/puncture-tables.cpp \
	   ./decoders/drm-decoder/utilities/deinterleaver.cpp \
	   ./decoders/drm-decoder/services/timesyncer.cpp \
	   ./decoders/drm-decoder/services/freqsyncer.cpp \
	   ./decoders/drm-decoder/services/time-correlator.cpp \
	   ./decoders/drm-decoder/scopes/eqdisplay.cpp \
	   ./decoders/drm-decoder/scopes/iqdisplay.cpp \
	   ./decoders/drm-decoder/signal-handling/referenceframe.cpp \
	   ./decoders/drm-decoder/signal-handling/equalizer-base.cpp \
	   ./decoders/drm-decoder/signal-handling/matrix2.cpp \
	   ./decoders/drm-decoder/signal-handling/equalizer-1.cpp \
	   ./decoders/drm-decoder/signal-handling/estimator-base.cpp \
#	   ./decoders/drm-decoder/signal-handling/equalizer-2.cpp \
	   ./decoders/drm-decoder/signal-handling/estimator-1.cpp 
}

fm	{

FORMS	+= ./decoders/fm-decoder/fm-decoder.ui
DEPENDPATH	*= \
		decoders/fm-decoder \
		decoders/fm-decoder/various \
		decoders/fm-decoder/rds

INCLUDEPATH	+= \
		decoders/fm-decoder \
		decoders/fm-decoder/various \
		decoders/fm-decoder/rds

HEADERS	+= \
	   ./decoders/fm-decoder/fm-decoder.h \
	   ./decoders/fm-decoder/fm-processor.h \
	   ./decoders/fm-decoder/fm-demodulator.h \
	   ./decoders/fm-decoder/various/sincos.h \
	   ./decoders/fm-decoder/various/pllC.h \
	   ./decoders/fm-decoder/various/newconverter.h \
	   ./decoders/fm-decoder/rds/rds-decoder.h \
	   ./decoders/fm-decoder/rds/rds-group.h \
	   ./decoders/fm-decoder/rds/rds-groupdecoder.h \
	   ./decoders/fm-decoder/rds/rds-blocksynchronizer.h

SOURCES	+= \
	   ./decoders/fm-decoder/fm-decoder.cpp \
           ./decoders/fm-decoder/fm-processor.cpp \
           ./decoders/fm-decoder/fm-demodulator.cpp \
           ./decoders/fm-decoder/various/sincos.cpp \
           ./decoders/fm-decoder/various/pllC.cpp \
	   ./decoders/fm-decoder/various/newconverter.cpp \
	   ./decoders/fm-decoder/rds/rds-decoder.cpp \
	   ./decoders/fm-decoder/rds/rds-group.cpp \
	   ./decoders/fm-decoder/rds/rds-groupdecoder.cpp \
	   ./decoders/fm-decoder/rds/rds-blocksynchronizer.cpp \
	   ./decoders/fm-decoder/rds/ebu-codetables.c
}

#       the SDRplay
#
sdrplay {
        DEFINES         += HAVE_SDRPLAY_V2
        FORMS           += ./devices/sdrplay-handler-v2/sdrplay-widget.ui
        DEPENDPATH     += ./devices/sdrplay-handler-v2
        INCLUDEPATH     += ./devices/sdrplay-handler-v2
        HEADERS         += ./devices/sdrplay-handler-v2/sdrplay-handler-v2.h \
                           ./devices/sdrplay-handler-v2/sdrplayselect.h
        SOURCES         += ./devices/sdrplay-handler-v2/sdrplay-handler-v2.cpp \
                           ./devices/sdrplay-handler-v2/sdrplayselect.cpp
}

hackrf	{
	DEFINES		+= HAVE_HACKRF
        FORMS           += ./devices/hackrf-handler/hackrf-widget.ui
        DEPENDPATH	+= ./devices/hackrf-handler
        INCLUDEPATH	+= ./devices/hackrf-handler
        HEADERS         += ./devices/hackrf-handler/hackrf-handler.h 
        SOURCES         += ./devices/hackrf-handler/hackrf-handler.cpp 
}

rtlsdr	{
	DEFINES		+= HAVE_RTLSDR
        FORMS           += ./devices/rtlsdr-handler/rtlsdr-widget.ui
        DEPENDPATH	+= ./devices/rtlsdr-handler
        INCLUDEPATH	+= ./devices/rtlsdr-handler
        HEADERS         += ./devices/rtlsdr-handler/rtlsdr-handler.h  \
	                   ./devices/rtlsdr-handler/dongleselect.h
        SOURCES         += ./devices/rtlsdr-handler/rtlsdr-handler.cpp \
	                   ./devices/rtlsdr-handler/dongleselect.cpp
}

lime  {
        DEFINES         += HAVE_LIME
        INCLUDEPATH     += ./devices/lime-handler
        DEPENDPATH      += ./devices/lime-handler
        HEADERS         += ./devices/lime-handler/lime-handler.h \
                           ./devices/lime-handler/lime-widget.h
        SOURCES         += ./devices/lime-handler/lime-handler.cpp
}

